### ISSUE TITLE
Updating error messages and javadocs

### ISSUE THREAD

**Issue by kskenandore** [CompSci-361/ChronoTimer#21]
Some of the error messages printed if the power is not on, etc. do not make sense for the method it is being printed within. They should be specific to what the user is trying to do.

**Comment by Amrykid** [comment]
@kskenandore I agree. That's why I asked if we should be throwing exceptions inside the ChronoTimer and handling them outside. From the outside, we can then print out error messages depending on if we're in unit tests or the simulator.
