### ISSUE TITLE
GUI Polish

### ISSUE THREAD

**Issue by Amrykid** [CompSci-361/ChronoTimer#55]
There some polishing that needs to be done on the GUI. We should take the time to bug test the GUI and make sure that everything is how it should be. Here is a non-exhaustive list of things I've found wrong with the GUI.

X The 'Reset' button doesn't clear the printerTextArea and jtextArea1 (where the queue is shown).

X The 'end race' button doesn't do this either.

X Race type buttons should be disabled until 'New Run' is clicked and disabled again when 'End Run' is pressed. (Uhm i think this is not how it should work. The race type needs to be selected before a new run can start, since you know, new run creates a new run of the given type. The problem Alex was having where the run was always Ind was because of this.)

X Everything should be disabled if the 'Power' isn't on.

X You shouldn't be able to connect a sensor with type 'none'.

X You shouldn't be able to connect a sensor to a channel that isn't enabled.

X Channels should be enable-able based on what race type is selected. Ind==1,2 ParInd==1-4 Grp==1,2 ParGrp==All

X Power off doesn't reset chronotimer correctly.

X Make sure ParGrp is working.

X Reset and Power should clear all the radio buttons and disconnect the sensors

X Print error message if race type is selected before power is enabled (Buttons disabled if no power)

X Print error message if swap, dnf, cancel, clear is selected before power is enabled. Nothing can be hit if power is off.

X Default text should be set to add racer if reset or power cycled. Works for most but clear messes this up.( Not sure what this means, I think it is fixed though)

X Reset should clear all text and radio buttons 

X Reset needs to reset the enabled channels

X New Run needs to reset the enabled channels

X GRP run end time triggers don't work. GRPRun problem

If there's anything else that needs to be done, lets list them here.

**Comment by cjscholl** [comment]
Reset and Endrun now clear the text areas.

**Comment by cjscholl** [comment]
Time should be disabled after "new run" is selected and re-enabled after a run has been ended, "end run".
