### ISSUE TITLE
NullPointerException when using GrpRun

### ISSUE THREAD

**Issue by Amrykid** [CompSci-361/ChronoTimer#67]
A NullPointerException is thrown when trying to move racers from the running queue to the finish queue before triggering channel 2.

This line is where it is occurring: https://github.com/CompSci-361/ChronoTimer/blob/master/src/core/GrpRun.java#L45

![image](https://user-images.githubusercontent.com/251501/39436150-d10e0dde-4c62-11e8-81f3-f7143860ab28.png)

**Comment by cjscholl** [comment]
fixed
